package luiss.it.Orientamento.dao;
// Generated 28-nov-2018 11.18.02 by Hibernate Tools 5.2.6.Final

/**
 * DipartimentiScelteGo generated by hbm2java
 */
public class DipartimentiScelteGo implements java.io.Serializable {

	private int id;
	private int idGo;
	private String dipartimento;

	public DipartimentiScelteGo() {
	}

	public DipartimentiScelteGo(int idGo, String dipartimento) {
		this.idGo = idGo;
		this.dipartimento = dipartimento;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getIdGo() {
		return this.idGo;
	}

	public void setIdGo(int idGo) {
		this.idGo = idGo;
	}

	public String getDipartimento() {
		return this.dipartimento;
	}

	public void setDipartimento(String dipartimento) {
		this.dipartimento = dipartimento;
	}

}
