package luiss.it.Orientamento.dao;
// Generated 28-nov-2018 11.18.02 by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * MiurScuole generated by hbm2java
 */
public class MiurScuole implements java.io.Serializable {

	private long idScuola;
	private String codScuola;
	private String denominazione;
	private String tipoScuolaMiurCod;
	private boolean stataleFlg;
	private String regione;
	private String prov;
	private String comune;
	private String codIstatMiur;
	private String cap;
	private String indirizzo;
	private String telefono;
	private boolean statoCaric;
	private Date dataCaric;
	private String livelloFunzionale;
	private String codiceScuolaRiferimento;
	private String tipologia;
	private String tipologiaSede;
	private String parita;
	private String targa;

	public MiurScuole() {
	}

	public MiurScuole(long idScuola, boolean stataleFlg, String codIstatMiur, boolean statoCaric) {
		this.idScuola = idScuola;
		this.stataleFlg = stataleFlg;
		this.codIstatMiur = codIstatMiur;
		this.statoCaric = statoCaric;
	}

	public MiurScuole(long idScuola, String codScuola, String denominazione, String tipoScuolaMiurCod,
			boolean stataleFlg, String regione, String prov, String comune, String codIstatMiur, String cap,
			String indirizzo, String telefono, boolean statoCaric, Date dataCaric, String livelloFunzionale,
			String codiceScuolaRiferimento, String tipologia, String tipologiaSede, String parita, String targa) {
		this.idScuola = idScuola;
		this.codScuola = codScuola;
		this.denominazione = denominazione;
		this.tipoScuolaMiurCod = tipoScuolaMiurCod;
		this.stataleFlg = stataleFlg;
		this.regione = regione;
		this.prov = prov;
		this.comune = comune;
		this.codIstatMiur = codIstatMiur;
		this.cap = cap;
		this.indirizzo = indirizzo;
		this.telefono = telefono;
		this.statoCaric = statoCaric;
		this.dataCaric = dataCaric;
		this.livelloFunzionale = livelloFunzionale;
		this.codiceScuolaRiferimento = codiceScuolaRiferimento;
		this.tipologia = tipologia;
		this.tipologiaSede = tipologiaSede;
		this.parita = parita;
		this.targa = targa;
	}

	public long getIdScuola() {
		return this.idScuola;
	}

	public void setIdScuola(long idScuola) {
		this.idScuola = idScuola;
	}

	public String getCodScuola() {
		return this.codScuola;
	}

	public void setCodScuola(String codScuola) {
		this.codScuola = codScuola;
	}

	public String getDenominazione() {
		return this.denominazione;
	}

	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione;
	}

	public String getTipoScuolaMiurCod() {
		return this.tipoScuolaMiurCod;
	}

	public void setTipoScuolaMiurCod(String tipoScuolaMiurCod) {
		this.tipoScuolaMiurCod = tipoScuolaMiurCod;
	}

	public boolean isStataleFlg() {
		return this.stataleFlg;
	}

	public void setStataleFlg(boolean stataleFlg) {
		this.stataleFlg = stataleFlg;
	}

	public String getRegione() {
		return this.regione;
	}

	public void setRegione(String regione) {
		this.regione = regione;
	}

	public String getProv() {
		return this.prov;
	}

	public void setProv(String prov) {
		this.prov = prov;
	}

	public String getComune() {
		return this.comune;
	}

	public void setComune(String comune) {
		this.comune = comune;
	}

	public String getCodIstatMiur() {
		return this.codIstatMiur;
	}

	public void setCodIstatMiur(String codIstatMiur) {
		this.codIstatMiur = codIstatMiur;
	}

	public String getCap() {
		return this.cap;
	}

	public void setCap(String cap) {
		this.cap = cap;
	}

	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public boolean isStatoCaric() {
		return this.statoCaric;
	}

	public void setStatoCaric(boolean statoCaric) {
		this.statoCaric = statoCaric;
	}

	public Date getDataCaric() {
		return this.dataCaric;
	}

	public void setDataCaric(Date dataCaric) {
		this.dataCaric = dataCaric;
	}

	public String getLivelloFunzionale() {
		return this.livelloFunzionale;
	}

	public void setLivelloFunzionale(String livelloFunzionale) {
		this.livelloFunzionale = livelloFunzionale;
	}

	public String getCodiceScuolaRiferimento() {
		return this.codiceScuolaRiferimento;
	}

	public void setCodiceScuolaRiferimento(String codiceScuolaRiferimento) {
		this.codiceScuolaRiferimento = codiceScuolaRiferimento;
	}

	public String getTipologia() {
		return this.tipologia;
	}

	public void setTipologia(String tipologia) {
		this.tipologia = tipologia;
	}

	public String getTipologiaSede() {
		return this.tipologiaSede;
	}

	public void setTipologiaSede(String tipologiaSede) {
		this.tipologiaSede = tipologiaSede;
	}

	public String getParita() {
		return this.parita;
	}

	public void setParita(String parita) {
		this.parita = parita;
	}

	public String getTarga() {
		return this.targa;
	}

	public void setTarga(String targa) {
		this.targa = targa;
	}

}
