package luiss.it.Orientamento.dao;
// Generated 28-nov-2018 11.18.02 by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * PeriodiGo generated by hbm2java
 */
public class PeriodiGo implements java.io.Serializable {

	private Integer id;
	private String descrizione;
	private Date giorno;
	private String visibile;

	public PeriodiGo() {
	}

	public PeriodiGo(String descrizione) {
		this.descrizione = descrizione;
	}

	public PeriodiGo(String descrizione, Date giorno, String visibile) {
		this.descrizione = descrizione;
		this.giorno = giorno;
		this.visibile = visibile;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Date getGiorno() {
		return this.giorno;
	}

	public void setGiorno(Date giorno) {
		this.giorno = giorno;
	}

	public String getVisibile() {
		return this.visibile;
	}

	public void setVisibile(String visibile) {
		this.visibile = visibile;
	}

}
