package luiss.it.TRIENNALI_INT.dao;
// Generated 15-nov-2018 17.14.10 by Hibernate Tools 5.2.6.Final

/**
 * PrewebId generated by hbm2java
 */
public class PrewebId implements java.io.Serializable {

	private String anno;
	private String sessione;
	private String cf;

	public PrewebId() {
	}

	public PrewebId(String anno, String sessione, String cf) {
		this.anno = anno;
		this.sessione = sessione;
		this.cf = cf;
	}

	public String getAnno() {
		return this.anno;
	}

	public void setAnno(String anno) {
		this.anno = anno;
	}

	public String getSessione() {
		return this.sessione;
	}

	public void setSessione(String sessione) {
		this.sessione = sessione;
	}

	public String getCf() {
		return this.cf;
	}

	public void setCf(String cf) {
		this.cf = cf;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrewebId))
			return false;
		PrewebId castOther = (PrewebId) other;

		return ((this.getAnno() == castOther.getAnno()) || (this.getAnno() != null && castOther.getAnno() != null
				&& this.getAnno().equals(castOther.getAnno())))
				&& ((this.getSessione() == castOther.getSessione()) || (this.getSessione() != null
						&& castOther.getSessione() != null && this.getSessione().equals(castOther.getSessione())))
				&& ((this.getCf() == castOther.getCf()) || (this.getCf() != null && castOther.getCf() != null
						&& this.getCf().equals(castOther.getCf())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAnno() == null ? 0 : this.getAnno().hashCode());
		result = 37 * result + (getSessione() == null ? 0 : this.getSessione().hashCode());
		result = 37 * result + (getCf() == null ? 0 : this.getCf().hashCode());
		return result;
	}

}
