package luiss.it.TRIENNALI_INT.dao;
// Generated 15-nov-2018 17.14.10 by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * Preweb generated by hbm2java
 */
public class Preweb implements java.io.Serializable {

	private PrewebId id;
	private String prewebCognome;
	private String prewebNome;
	private String prewebSesso;
	private String prewebNascom;
	private String prewebNaspr;
	private Date prewebNasdata;
	private String prewebNazione;
	private String prewebRescom;
	private String prewebResind;
	private String prewebRespr;
	private String prewebRescap;
	private String prewebTelefono;
	private String prewebCellulare;
	private String prewebEmail;
	private String prewebIstscol;
	private String prewebIstcom;
	private String prewebIstind;
	private String prewebIstpr;
	private String prewebIstcap;
	private String prewebIsttipo;
	private String prewebFac;
	private String prewebCorsolau;
	private String prewebTipopag;
	private Date prewebDatapag;
	private String prewebMedia3;
	private String prewebMedia4;
	private String prewebSedesost;
	private Date prewebDatadomanda;
	private String prewebConfpag;
	private Date prewebDatamod;
	private String prewebTitstr3;
	private String prewebTitstr4;
	private String prewebProg;
	private String prewebLinguaIi;
	private String prewebVoto60;
	private String prewebVoto100;
	private String prewebTitstr;
	private String prewebAnnodipl;
	private String prewebAutentica;
	private String prewebPagella;
	private String prewebIstemail;
	private String prewebIsttel;
	private Integer prewebDesk;
	private String prewebConsauto;
	private String prewebNazOrdinamento;
	private String prewebAmme;
	private double prewebMedtot;
	private double prewebMedtst;
	private double prewebVotofin;
	private String prewebFilpre1;
	private Integer prewebGraduatoria;
	private String prewebSegno;
	private Integer prewebNdesatte;
	private Integer prewebNderrate;
	private Integer prewebNdnonris;
	private String prewenNazioneNascita;
	private String prewebEuNoneu;
	private String prewebStateProvinceRes;
	private String prewebNazioneRes;
	private String prewebFax;
	private String prewebNazioneScuola;
	private String prewebWebScuola;
	private String prewebMmSd;
	private String prewebYyyySd;
	private String prewebMmGd;
	private String prewebYyyyGd;
	private String prewebMmEgd;
	private String prewebYyyyEgd;
	private String prewebAnniScuola;
	private Integer prewebCrticalReadingScore;
	private Integer prewebMathematicsScore;
	private Integer prewebWritingScore;
	private Integer prewebTotale;
	private String prewebAltreQualifiche1;
	private String prewebAltreQualifiche2;
	private String prewebAltreQualifiche3;
	private String prewebStateProvinceScuola;
	private Integer prewebAct;
	private String prewebPrivacy;

	public Preweb() {
	}

	public Preweb(PrewebId id, String prewebIstemail, String prewebIsttel, String prewebAmme, double prewebMedtot,
			double prewebMedtst, double prewebVotofin, String prewebFilpre1, Integer prewebGraduatoria,
			String prewebSegno, Integer prewebNdesatte, Integer prewebNderrate, Integer prewebNdnonris) {
		this.id = id;
		this.prewebIstemail = prewebIstemail;
		this.prewebIsttel = prewebIsttel;
		this.prewebAmme = prewebAmme;
		this.prewebMedtot = prewebMedtot;
		this.prewebMedtst = prewebMedtst;
		this.prewebVotofin = prewebVotofin;
		this.prewebFilpre1 = prewebFilpre1;
		this.prewebGraduatoria = prewebGraduatoria;
		this.prewebSegno = prewebSegno;
		this.prewebNdesatte = prewebNdesatte;
		this.prewebNderrate = prewebNderrate;
		this.prewebNdnonris = prewebNdnonris;
	}

	public Preweb(PrewebId id, String prewebCognome, String prewebNome, String prewebSesso, String prewebNascom,
			String prewebNaspr, Date prewebNasdata, String prewebNazione, String prewebRescom, String prewebResind,
			String prewebRespr, String prewebRescap, String prewebTelefono, String prewebCellulare, String prewebEmail,
			String prewebIstscol, String prewebIstcom, String prewebIstind, String prewebIstpr, String prewebIstcap,
			String prewebIsttipo, String prewebFac, String prewebCorsolau, String prewebTipopag, Date prewebDatapag,
			String prewebMedia3, String prewebMedia4, String prewebSedesost, Date prewebDatadomanda,
			String prewebConfpag, Date prewebDatamod, String prewebTitstr3, String prewebTitstr4, String prewebProg,
			String prewebLinguaIi, String prewebVoto60, String prewebVoto100, String prewebTitstr,
			String prewebAnnodipl, String prewebAutentica, String prewebPagella, String prewebIstemail,
			String prewebIsttel, Integer prewebDesk, String prewebConsauto, String prewebNazOrdinamento,
			String prewebAmme, double prewebMedtot, double prewebMedtst, double prewebVotofin, String prewebFilpre1,
			Integer prewebGraduatoria, String prewebSegno, Integer prewebNdesatte, Integer prewebNderrate,
			Integer prewebNdnonris, String prewenNazioneNascita, String prewebEuNoneu, String prewebStateProvinceRes,
			String prewebNazioneRes, String prewebFax, String prewebNazioneScuola, String prewebWebScuola,
			String prewebMmSd, String prewebYyyySd, String prewebMmGd, String prewebYyyyGd, String prewebMmEgd,
			String prewebYyyyEgd, String prewebAnniScuola, Integer prewebCrticalReadingScore,
			Integer prewebMathematicsScore, Integer prewebWritingScore, Integer prewebTotale,
			String prewebAltreQualifiche1, String prewebAltreQualifiche2, String prewebAltreQualifiche3,
			String prewebStateProvinceScuola, Integer prewebAct, String prewebPrivacy) {
		this.id = id;
		this.prewebCognome = prewebCognome;
		this.prewebNome = prewebNome;
		this.prewebSesso = prewebSesso;
		this.prewebNascom = prewebNascom;
		this.prewebNaspr = prewebNaspr;
		this.prewebNasdata = prewebNasdata;
		this.prewebNazione = prewebNazione;
		this.prewebRescom = prewebRescom;
		this.prewebResind = prewebResind;
		this.prewebRespr = prewebRespr;
		this.prewebRescap = prewebRescap;
		this.prewebTelefono = prewebTelefono;
		this.prewebCellulare = prewebCellulare;
		this.prewebEmail = prewebEmail;
		this.prewebIstscol = prewebIstscol;
		this.prewebIstcom = prewebIstcom;
		this.prewebIstind = prewebIstind;
		this.prewebIstpr = prewebIstpr;
		this.prewebIstcap = prewebIstcap;
		this.prewebIsttipo = prewebIsttipo;
		this.prewebFac = prewebFac;
		this.prewebCorsolau = prewebCorsolau;
		this.prewebTipopag = prewebTipopag;
		this.prewebDatapag = prewebDatapag;
		this.prewebMedia3 = prewebMedia3;
		this.prewebMedia4 = prewebMedia4;
		this.prewebSedesost = prewebSedesost;
		this.prewebDatadomanda = prewebDatadomanda;
		this.prewebConfpag = prewebConfpag;
		this.prewebDatamod = prewebDatamod;
		this.prewebTitstr3 = prewebTitstr3;
		this.prewebTitstr4 = prewebTitstr4;
		this.prewebProg = prewebProg;
		this.prewebLinguaIi = prewebLinguaIi;
		this.prewebVoto60 = prewebVoto60;
		this.prewebVoto100 = prewebVoto100;
		this.prewebTitstr = prewebTitstr;
		this.prewebAnnodipl = prewebAnnodipl;
		this.prewebAutentica = prewebAutentica;
		this.prewebPagella = prewebPagella;
		this.prewebIstemail = prewebIstemail;
		this.prewebIsttel = prewebIsttel;
		this.prewebDesk = prewebDesk;
		this.prewebConsauto = prewebConsauto;
		this.prewebNazOrdinamento = prewebNazOrdinamento;
		this.prewebAmme = prewebAmme;
		this.prewebMedtot = prewebMedtot;
		this.prewebMedtst = prewebMedtst;
		this.prewebVotofin = prewebVotofin;
		this.prewebFilpre1 = prewebFilpre1;
		this.prewebGraduatoria = prewebGraduatoria;
		this.prewebSegno = prewebSegno;
		this.prewebNdesatte = prewebNdesatte;
		this.prewebNderrate = prewebNderrate;
		this.prewebNdnonris = prewebNdnonris;
		this.prewenNazioneNascita = prewenNazioneNascita;
		this.prewebEuNoneu = prewebEuNoneu;
		this.prewebStateProvinceRes = prewebStateProvinceRes;
		this.prewebNazioneRes = prewebNazioneRes;
		this.prewebFax = prewebFax;
		this.prewebNazioneScuola = prewebNazioneScuola;
		this.prewebWebScuola = prewebWebScuola;
		this.prewebMmSd = prewebMmSd;
		this.prewebYyyySd = prewebYyyySd;
		this.prewebMmGd = prewebMmGd;
		this.prewebYyyyGd = prewebYyyyGd;
		this.prewebMmEgd = prewebMmEgd;
		this.prewebYyyyEgd = prewebYyyyEgd;
		this.prewebAnniScuola = prewebAnniScuola;
		this.prewebCrticalReadingScore = prewebCrticalReadingScore;
		this.prewebMathematicsScore = prewebMathematicsScore;
		this.prewebWritingScore = prewebWritingScore;
		this.prewebTotale = prewebTotale;
		this.prewebAltreQualifiche1 = prewebAltreQualifiche1;
		this.prewebAltreQualifiche2 = prewebAltreQualifiche2;
		this.prewebAltreQualifiche3 = prewebAltreQualifiche3;
		this.prewebStateProvinceScuola = prewebStateProvinceScuola;
		this.prewebAct = prewebAct;
		this.prewebPrivacy = prewebPrivacy;
	}

	public PrewebId getId() {
		return this.id;
	}

	public void setId(PrewebId id) {
		this.id = id;
	}

	public String getPrewebCognome() {
		return this.prewebCognome;
	}

	public void setPrewebCognome(String prewebCognome) {
		this.prewebCognome = prewebCognome;
	}

	public String getPrewebNome() {
		return this.prewebNome;
	}

	public void setPrewebNome(String prewebNome) {
		this.prewebNome = prewebNome;
	}

	public String getPrewebSesso() {
		return this.prewebSesso;
	}

	public void setPrewebSesso(String prewebSesso) {
		this.prewebSesso = prewebSesso;
	}

	public String getPrewebNascom() {
		return this.prewebNascom;
	}

	public void setPrewebNascom(String prewebNascom) {
		this.prewebNascom = prewebNascom;
	}

	public String getPrewebNaspr() {
		return this.prewebNaspr;
	}

	public void setPrewebNaspr(String prewebNaspr) {
		this.prewebNaspr = prewebNaspr;
	}

	public Date getPrewebNasdata() {
		return this.prewebNasdata;
	}

	public void setPrewebNasdata(Date prewebNasdata) {
		this.prewebNasdata = prewebNasdata;
	}

	public String getPrewebNazione() {
		return this.prewebNazione;
	}

	public void setPrewebNazione(String prewebNazione) {
		this.prewebNazione = prewebNazione;
	}

	public String getPrewebRescom() {
		return this.prewebRescom;
	}

	public void setPrewebRescom(String prewebRescom) {
		this.prewebRescom = prewebRescom;
	}

	public String getPrewebResind() {
		return this.prewebResind;
	}

	public void setPrewebResind(String prewebResind) {
		this.prewebResind = prewebResind;
	}

	public String getPrewebRespr() {
		return this.prewebRespr;
	}

	public void setPrewebRespr(String prewebRespr) {
		this.prewebRespr = prewebRespr;
	}

	public String getPrewebRescap() {
		return this.prewebRescap;
	}

	public void setPrewebRescap(String prewebRescap) {
		this.prewebRescap = prewebRescap;
	}

	public String getPrewebTelefono() {
		return this.prewebTelefono;
	}

	public void setPrewebTelefono(String prewebTelefono) {
		this.prewebTelefono = prewebTelefono;
	}

	public String getPrewebCellulare() {
		return this.prewebCellulare;
	}

	public void setPrewebCellulare(String prewebCellulare) {
		this.prewebCellulare = prewebCellulare;
	}

	public String getPrewebEmail() {
		return this.prewebEmail;
	}

	public void setPrewebEmail(String prewebEmail) {
		this.prewebEmail = prewebEmail;
	}

	public String getPrewebIstscol() {
		return this.prewebIstscol;
	}

	public void setPrewebIstscol(String prewebIstscol) {
		this.prewebIstscol = prewebIstscol;
	}

	public String getPrewebIstcom() {
		return this.prewebIstcom;
	}

	public void setPrewebIstcom(String prewebIstcom) {
		this.prewebIstcom = prewebIstcom;
	}

	public String getPrewebIstind() {
		return this.prewebIstind;
	}

	public void setPrewebIstind(String prewebIstind) {
		this.prewebIstind = prewebIstind;
	}

	public String getPrewebIstpr() {
		return this.prewebIstpr;
	}

	public void setPrewebIstpr(String prewebIstpr) {
		this.prewebIstpr = prewebIstpr;
	}

	public String getPrewebIstcap() {
		return this.prewebIstcap;
	}

	public void setPrewebIstcap(String prewebIstcap) {
		this.prewebIstcap = prewebIstcap;
	}

	public String getPrewebIsttipo() {
		return this.prewebIsttipo;
	}

	public void setPrewebIsttipo(String prewebIsttipo) {
		this.prewebIsttipo = prewebIsttipo;
	}

	public String getPrewebFac() {
		return this.prewebFac;
	}

	public void setPrewebFac(String prewebFac) {
		this.prewebFac = prewebFac;
	}

	public String getPrewebCorsolau() {
		return this.prewebCorsolau;
	}

	public void setPrewebCorsolau(String prewebCorsolau) {
		this.prewebCorsolau = prewebCorsolau;
	}

	public String getPrewebTipopag() {
		return this.prewebTipopag;
	}

	public void setPrewebTipopag(String prewebTipopag) {
		this.prewebTipopag = prewebTipopag;
	}

	public Date getPrewebDatapag() {
		return this.prewebDatapag;
	}

	public void setPrewebDatapag(Date prewebDatapag) {
		this.prewebDatapag = prewebDatapag;
	}

	public String getPrewebMedia3() {
		return this.prewebMedia3;
	}

	public void setPrewebMedia3(String prewebMedia3) {
		this.prewebMedia3 = prewebMedia3;
	}

	public String getPrewebMedia4() {
		return this.prewebMedia4;
	}

	public void setPrewebMedia4(String prewebMedia4) {
		this.prewebMedia4 = prewebMedia4;
	}

	public String getPrewebSedesost() {
		return this.prewebSedesost;
	}

	public void setPrewebSedesost(String prewebSedesost) {
		this.prewebSedesost = prewebSedesost;
	}

	public Date getPrewebDatadomanda() {
		return this.prewebDatadomanda;
	}

	public void setPrewebDatadomanda(Date prewebDatadomanda) {
		this.prewebDatadomanda = prewebDatadomanda;
	}

	public String getPrewebConfpag() {
		return this.prewebConfpag;
	}

	public void setPrewebConfpag(String prewebConfpag) {
		this.prewebConfpag = prewebConfpag;
	}

	public Date getPrewebDatamod() {
		return this.prewebDatamod;
	}

	public void setPrewebDatamod(Date prewebDatamod) {
		this.prewebDatamod = prewebDatamod;
	}

	public String getPrewebTitstr3() {
		return this.prewebTitstr3;
	}

	public void setPrewebTitstr3(String prewebTitstr3) {
		this.prewebTitstr3 = prewebTitstr3;
	}

	public String getPrewebTitstr4() {
		return this.prewebTitstr4;
	}

	public void setPrewebTitstr4(String prewebTitstr4) {
		this.prewebTitstr4 = prewebTitstr4;
	}

	public String getPrewebProg() {
		return this.prewebProg;
	}

	public void setPrewebProg(String prewebProg) {
		this.prewebProg = prewebProg;
	}

	public String getPrewebLinguaIi() {
		return this.prewebLinguaIi;
	}

	public void setPrewebLinguaIi(String prewebLinguaIi) {
		this.prewebLinguaIi = prewebLinguaIi;
	}

	public String getPrewebVoto60() {
		return this.prewebVoto60;
	}

	public void setPrewebVoto60(String prewebVoto60) {
		this.prewebVoto60 = prewebVoto60;
	}

	public String getPrewebVoto100() {
		return this.prewebVoto100;
	}

	public void setPrewebVoto100(String prewebVoto100) {
		this.prewebVoto100 = prewebVoto100;
	}

	public String getPrewebTitstr() {
		return this.prewebTitstr;
	}

	public void setPrewebTitstr(String prewebTitstr) {
		this.prewebTitstr = prewebTitstr;
	}

	public String getPrewebAnnodipl() {
		return this.prewebAnnodipl;
	}

	public void setPrewebAnnodipl(String prewebAnnodipl) {
		this.prewebAnnodipl = prewebAnnodipl;
	}

	public String getPrewebAutentica() {
		return this.prewebAutentica;
	}

	public void setPrewebAutentica(String prewebAutentica) {
		this.prewebAutentica = prewebAutentica;
	}

	public String getPrewebPagella() {
		return this.prewebPagella;
	}

	public void setPrewebPagella(String prewebPagella) {
		this.prewebPagella = prewebPagella;
	}

	public String getPrewebIstemail() {
		return this.prewebIstemail;
	}

	public void setPrewebIstemail(String prewebIstemail) {
		this.prewebIstemail = prewebIstemail;
	}

	public String getPrewebIsttel() {
		return this.prewebIsttel;
	}

	public void setPrewebIsttel(String prewebIsttel) {
		this.prewebIsttel = prewebIsttel;
	}

	public Integer getPrewebDesk() {
		return this.prewebDesk;
	}

	public void setPrewebDesk(Integer prewebDesk) {
		this.prewebDesk = prewebDesk;
	}

	public String getPrewebConsauto() {
		return this.prewebConsauto;
	}

	public void setPrewebConsauto(String prewebConsauto) {
		this.prewebConsauto = prewebConsauto;
	}

	public String getPrewebNazOrdinamento() {
		return this.prewebNazOrdinamento;
	}

	public void setPrewebNazOrdinamento(String prewebNazOrdinamento) {
		this.prewebNazOrdinamento = prewebNazOrdinamento;
	}

	public String getPrewebAmme() {
		return this.prewebAmme;
	}

	public void setPrewebAmme(String prewebAmme) {
		this.prewebAmme = prewebAmme;
	}

	public double getPrewebMedtot() {
		return this.prewebMedtot;
	}

	public void setPrewebMedtot(double prewebMedtot) {
		this.prewebMedtot = prewebMedtot;
	}

	public double getPrewebMedtst() {
		return this.prewebMedtst;
	}

	public void setPrewebMedtst(double prewebMedtst) {
		this.prewebMedtst = prewebMedtst;
	}

	public double getPrewebVotofin() {
		return this.prewebVotofin;
	}

	public void setPrewebVotofin(double prewebVotofin) {
		this.prewebVotofin = prewebVotofin;
	}

	public String getPrewebFilpre1() {
		return this.prewebFilpre1;
	}

	public void setPrewebFilpre1(String prewebFilpre1) {
		this.prewebFilpre1 = prewebFilpre1;
	}

	public Integer getPrewebGraduatoria() {
		return this.prewebGraduatoria;
	}

	public void setPrewebGraduatoria(Integer prewebGraduatoria) {
		this.prewebGraduatoria = prewebGraduatoria;
	}

	public String getPrewebSegno() {
		return this.prewebSegno;
	}

	public void setPrewebSegno(String prewebSegno) {
		this.prewebSegno = prewebSegno;
	}

	public Integer getPrewebNdesatte() {
		return this.prewebNdesatte;
	}

	public void setPrewebNdesatte(Integer prewebNdesatte) {
		this.prewebNdesatte = prewebNdesatte;
	}

	public Integer getPrewebNderrate() {
		return this.prewebNderrate;
	}

	public void setPrewebNderrate(Integer prewebNderrate) {
		this.prewebNderrate = prewebNderrate;
	}

	public Integer getPrewebNdnonris() {
		return this.prewebNdnonris;
	}

	public void setPrewebNdnonris(Integer prewebNdnonris) {
		this.prewebNdnonris = prewebNdnonris;
	}

	public String getPrewenNazioneNascita() {
		return this.prewenNazioneNascita;
	}

	public void setPrewenNazioneNascita(String prewenNazioneNascita) {
		this.prewenNazioneNascita = prewenNazioneNascita;
	}

	public String getPrewebEuNoneu() {
		return this.prewebEuNoneu;
	}

	public void setPrewebEuNoneu(String prewebEuNoneu) {
		this.prewebEuNoneu = prewebEuNoneu;
	}

	public String getPrewebStateProvinceRes() {
		return this.prewebStateProvinceRes;
	}

	public void setPrewebStateProvinceRes(String prewebStateProvinceRes) {
		this.prewebStateProvinceRes = prewebStateProvinceRes;
	}

	public String getPrewebNazioneRes() {
		return this.prewebNazioneRes;
	}

	public void setPrewebNazioneRes(String prewebNazioneRes) {
		this.prewebNazioneRes = prewebNazioneRes;
	}

	public String getPrewebFax() {
		return this.prewebFax;
	}

	public void setPrewebFax(String prewebFax) {
		this.prewebFax = prewebFax;
	}

	public String getPrewebNazioneScuola() {
		return this.prewebNazioneScuola;
	}

	public void setPrewebNazioneScuola(String prewebNazioneScuola) {
		this.prewebNazioneScuola = prewebNazioneScuola;
	}

	public String getPrewebWebScuola() {
		return this.prewebWebScuola;
	}

	public void setPrewebWebScuola(String prewebWebScuola) {
		this.prewebWebScuola = prewebWebScuola;
	}

	public String getPrewebMmSd() {
		return this.prewebMmSd;
	}

	public void setPrewebMmSd(String prewebMmSd) {
		this.prewebMmSd = prewebMmSd;
	}

	public String getPrewebYyyySd() {
		return this.prewebYyyySd;
	}

	public void setPrewebYyyySd(String prewebYyyySd) {
		this.prewebYyyySd = prewebYyyySd;
	}

	public String getPrewebMmGd() {
		return this.prewebMmGd;
	}

	public void setPrewebMmGd(String prewebMmGd) {
		this.prewebMmGd = prewebMmGd;
	}

	public String getPrewebYyyyGd() {
		return this.prewebYyyyGd;
	}

	public void setPrewebYyyyGd(String prewebYyyyGd) {
		this.prewebYyyyGd = prewebYyyyGd;
	}

	public String getPrewebMmEgd() {
		return this.prewebMmEgd;
	}

	public void setPrewebMmEgd(String prewebMmEgd) {
		this.prewebMmEgd = prewebMmEgd;
	}

	public String getPrewebYyyyEgd() {
		return this.prewebYyyyEgd;
	}

	public void setPrewebYyyyEgd(String prewebYyyyEgd) {
		this.prewebYyyyEgd = prewebYyyyEgd;
	}

	public String getPrewebAnniScuola() {
		return this.prewebAnniScuola;
	}

	public void setPrewebAnniScuola(String prewebAnniScuola) {
		this.prewebAnniScuola = prewebAnniScuola;
	}

	public Integer getPrewebCrticalReadingScore() {
		return this.prewebCrticalReadingScore;
	}

	public void setPrewebCrticalReadingScore(Integer prewebCrticalReadingScore) {
		this.prewebCrticalReadingScore = prewebCrticalReadingScore;
	}

	public Integer getPrewebMathematicsScore() {
		return this.prewebMathematicsScore;
	}

	public void setPrewebMathematicsScore(Integer prewebMathematicsScore) {
		this.prewebMathematicsScore = prewebMathematicsScore;
	}

	public Integer getPrewebWritingScore() {
		return this.prewebWritingScore;
	}

	public void setPrewebWritingScore(Integer prewebWritingScore) {
		this.prewebWritingScore = prewebWritingScore;
	}

	public Integer getPrewebTotale() {
		return this.prewebTotale;
	}

	public void setPrewebTotale(Integer prewebTotale) {
		this.prewebTotale = prewebTotale;
	}

	public String getPrewebAltreQualifiche1() {
		return this.prewebAltreQualifiche1;
	}

	public void setPrewebAltreQualifiche1(String prewebAltreQualifiche1) {
		this.prewebAltreQualifiche1 = prewebAltreQualifiche1;
	}

	public String getPrewebAltreQualifiche2() {
		return this.prewebAltreQualifiche2;
	}

	public void setPrewebAltreQualifiche2(String prewebAltreQualifiche2) {
		this.prewebAltreQualifiche2 = prewebAltreQualifiche2;
	}

	public String getPrewebAltreQualifiche3() {
		return this.prewebAltreQualifiche3;
	}

	public void setPrewebAltreQualifiche3(String prewebAltreQualifiche3) {
		this.prewebAltreQualifiche3 = prewebAltreQualifiche3;
	}

	public String getPrewebStateProvinceScuola() {
		return this.prewebStateProvinceScuola;
	}

	public void setPrewebStateProvinceScuola(String prewebStateProvinceScuola) {
		this.prewebStateProvinceScuola = prewebStateProvinceScuola;
	}

	public Integer getPrewebAct() {
		return this.prewebAct;
	}

	public void setPrewebAct(Integer prewebAct) {
		this.prewebAct = prewebAct;
	}

	public String getPrewebPrivacy() {
		return this.prewebPrivacy;
	}

	public void setPrewebPrivacy(String prewebPrivacy) {
		this.prewebPrivacy = prewebPrivacy;
	}

}
