package luiss.it.TRIENNALI.dao;
// Generated 29-nov-2018 18.33.34 by Hibernate Tools 5.2.6.Final

/**
 * CdlsceltaId generated by hbm2java
 */
public class CdlsceltaId implements java.io.Serializable {

	private String fac;
	private String cds;

	public CdlsceltaId() {
	}

	public CdlsceltaId(String fac, String cds) {
		this.fac = fac;
		this.cds = cds;
	}

	public String getFac() {
		return this.fac;
	}

	public void setFac(String fac) {
		this.fac = fac;
	}

	public String getCds() {
		return this.cds;
	}

	public void setCds(String cds) {
		this.cds = cds;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CdlsceltaId))
			return false;
		CdlsceltaId castOther = (CdlsceltaId) other;

		return ((this.getFac() == castOther.getFac())
				|| (this.getFac() != null && castOther.getFac() != null && this.getFac().equals(castOther.getFac())))
				&& ((this.getCds() == castOther.getCds()) || (this.getCds() != null && castOther.getCds() != null
						&& this.getCds().equals(castOther.getCds())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFac() == null ? 0 : this.getFac().hashCode());
		result = 37 * result + (getCds() == null ? 0 : this.getCds().hashCode());
		return result;
	}

}
