package luiss.it.TRIENNALI.dao;
// Generated 29-nov-2018 18.33.34 by Hibernate Tools 5.2.6.Final

/**
 * Diplomi generated by hbm2java
 */
public class Diplomi implements java.io.Serializable {

	private String diplomaId;
	private String denominazione;
	private String denomMiur;

	public Diplomi() {
	}

	public Diplomi(String diplomaId) {
		this.diplomaId = diplomaId;
	}

	public Diplomi(String diplomaId, String denominazione, String denomMiur) {
		this.diplomaId = diplomaId;
		this.denominazione = denominazione;
		this.denomMiur = denomMiur;
	}

	public String getDiplomaId() {
		return this.diplomaId;
	}

	public void setDiplomaId(String diplomaId) {
		this.diplomaId = diplomaId;
	}

	public String getDenominazione() {
		return this.denominazione;
	}

	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione;
	}

	public String getDenomMiur() {
		return this.denomMiur;
	}

	public void setDenomMiur(String denomMiur) {
		this.denomMiur = denomMiur;
	}

}
