package luiss.it.MAGISTRALI_INT.dao;
// Generated 15-nov-2018 17.05.56 by Hibernate Tools 5.2.6.Final

/**
 * CdlsceltaId generated by hbm2java
 */
public class CdlsceltaId implements java.io.Serializable {

	private String fac;
	private String cds;
	private String ind;

	public CdlsceltaId() {
	}

	public CdlsceltaId(String fac, String cds, String ind) {
		this.fac = fac;
		this.cds = cds;
		this.ind = ind;
	}

	public String getFac() {
		return this.fac;
	}

	public void setFac(String fac) {
		this.fac = fac;
	}

	public String getCds() {
		return this.cds;
	}

	public void setCds(String cds) {
		this.cds = cds;
	}

	public String getInd() {
		return this.ind;
	}

	public void setInd(String ind) {
		this.ind = ind;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CdlsceltaId))
			return false;
		CdlsceltaId castOther = (CdlsceltaId) other;

		return ((this.getFac() == castOther.getFac())
				|| (this.getFac() != null && castOther.getFac() != null && this.getFac().equals(castOther.getFac())))
				&& ((this.getCds() == castOther.getCds()) || (this.getCds() != null && castOther.getCds() != null
						&& this.getCds().equals(castOther.getCds())))
				&& ((this.getInd() == castOther.getInd()) || (this.getInd() != null && castOther.getInd() != null
						&& this.getInd().equals(castOther.getInd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFac() == null ? 0 : this.getFac().hashCode());
		result = 37 * result + (getCds() == null ? 0 : this.getCds().hashCode());
		result = 37 * result + (getInd() == null ? 0 : this.getInd().hashCode());
		return result;
	}

}
