package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

/**
 * AnniAccademici generated by hbm2java
 */
public class AnniAccademici implements java.io.Serializable {

	private Integer id;
	private String des;

	public AnniAccademici() {
	}

	public AnniAccademici(Integer id) {
		this.id = id;
	}

	public AnniAccademici(Integer id, String des) {
		this.id = id;
		this.des = des;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDes() {
		return this.des;
	}

	public void setDes(String des) {
		this.des = des;
	}

}
