package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

/**
 * Cds generated by hbm2java
 */
public class Cds implements java.io.Serializable {

	private String cod;
	private String des;

	public Cds() {
	}

	public Cds(String cod) {
		this.cod = cod;
	}

	public Cds(String cod, String des) {
		this.cod = cod;
		this.des = des;
	}

	public String getCod() {
		return this.cod;
	}

	public void setCod(String cod) {
		this.cod = cod;
	}

	public String getDes() {
		return this.des;
	}

	public void setDes(String des) {
		this.des = des;
	}

}
