package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

/**
 * Comuni generated by hbm2java
 */
public class Comuni implements java.io.Serializable {

	private Integer id;
	private String comune;
	private String codiceCatastale;
	private Integer idProvince;

	public Comuni() {
	}

	public Comuni(String comune, String codiceCatastale, Integer idProvince) {
		this.comune = comune;
		this.codiceCatastale = codiceCatastale;
		this.idProvince = idProvince;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getComune() {
		return this.comune;
	}

	public void setComune(String comune) {
		this.comune = comune;
	}

	public String getCodiceCatastale() {
		return this.codiceCatastale;
	}

	public void setCodiceCatastale(String codiceCatastale) {
		this.codiceCatastale = codiceCatastale;
	}

	public Integer getIdProvince() {
		return this.idProvince;
	}

	public void setIdProvince(Integer idProvince) {
		this.idProvince = idProvince;
	}

}
