package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * Config generated by hbm2java
 */
public class Config implements java.io.Serializable {

	private Integer id;
	private String residenza;
	private String recapiti;
	private String diploma;
	private String laurea;
	private String genitore;
	private String fotografia;
	private String urlOk;
	private String urlKo;
	private Date scadenzaVisibilita;

	public Config() {
	}

	public Config(Integer id, String residenza, String recapiti, String diploma, String laurea, String genitore,
			String fotografia) {
		this.id = id;
		this.residenza = residenza;
		this.recapiti = recapiti;
		this.diploma = diploma;
		this.laurea = laurea;
		this.genitore = genitore;
		this.fotografia = fotografia;
	}

	public Config(Integer id, String residenza, String recapiti, String diploma, String laurea, String genitore,
			String fotografia, String urlOk, String urlKo, Date scadenzaVisibilita) {
		this.id = id;
		this.residenza = residenza;
		this.recapiti = recapiti;
		this.diploma = diploma;
		this.laurea = laurea;
		this.genitore = genitore;
		this.fotografia = fotografia;
		this.urlOk = urlOk;
		this.urlKo = urlKo;
		this.scadenzaVisibilita = scadenzaVisibilita;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getResidenza() {
		return this.residenza;
	}

	public void setResidenza(String residenza) {
		this.residenza = residenza;
	}

	public String getRecapiti() {
		return this.recapiti;
	}

	public void setRecapiti(String recapiti) {
		this.recapiti = recapiti;
	}

	public String getDiploma() {
		return this.diploma;
	}

	public void setDiploma(String diploma) {
		this.diploma = diploma;
	}

	public String getLaurea() {
		return this.laurea;
	}

	public void setLaurea(String laurea) {
		this.laurea = laurea;
	}

	public String getGenitore() {
		return this.genitore;
	}

	public void setGenitore(String genitore) {
		this.genitore = genitore;
	}

	public String getFotografia() {
		return this.fotografia;
	}

	public void setFotografia(String fotografia) {
		this.fotografia = fotografia;
	}

	public String getUrlOk() {
		return this.urlOk;
	}

	public void setUrlOk(String urlOk) {
		this.urlOk = urlOk;
	}

	public String getUrlKo() {
		return this.urlKo;
	}

	public void setUrlKo(String urlKo) {
		this.urlKo = urlKo;
	}

	public Date getScadenzaVisibilita() {
		return this.scadenzaVisibilita;
	}

	public void setScadenzaVisibilita(Date scadenzaVisibilita) {
		this.scadenzaVisibilita = scadenzaVisibilita;
	}

}
