package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

/**
 * Controlli generated by hbm2java
 */
public class Controlli implements java.io.Serializable {

	private Integer id;
	private Integer idContesti;
	private String inputName;
	private String obbligatorio;
	private String regExp;
	private Integer min;
	private Integer max;

	public Controlli() {
	}

	public Controlli(Integer idContesti, String inputName, String obbligatorio, String regExp, Integer min,
			Integer max) {
		this.idContesti = idContesti;
		this.inputName = inputName;
		this.obbligatorio = obbligatorio;
		this.regExp = regExp;
		this.min = min;
		this.max = max;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdContesti() {
		return this.idContesti;
	}

	public void setIdContesti(Integer idContesti) {
		this.idContesti = idContesti;
	}

	public String getInputName() {
		return this.inputName;
	}

	public void setInputName(String inputName) {
		this.inputName = inputName;
	}

	public String getObbligatorio() {
		return this.obbligatorio;
	}

	public void setObbligatorio(String obbligatorio) {
		this.obbligatorio = obbligatorio;
	}

	public String getRegExp() {
		return this.regExp;
	}

	public void setRegExp(String regExp) {
		this.regExp = regExp;
	}

	public Integer getMin() {
		return this.min;
	}

	public void setMin(Integer min) {
		this.min = min;
	}

	public Integer getMax() {
		return this.max;
	}

	public void setMax(Integer max) {
		this.max = max;
	}

}
