package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

/**
 * Continenti generated by hbm2java
 */
public class Continenti implements java.io.Serializable {

	private Integer id;
	private String continente;

	public Continenti() {
	}

	public Continenti(String continente) {
		this.continente = continente;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContinente() {
		return this.continente;
	}

	public void setContinente(String continente) {
		this.continente = continente;
	}

}
