package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * DatiSportivi generated by hbm2java
 */
public class DatiSportivi implements java.io.Serializable {

	private Integer id;
	private Integer idDisciplineSportive;
	private Integer idLivelliSportivi;
	private String societaDiAppertenenza;
	private Integer annoInizioAgonismo;
	private Integer idPersone;
	private String letteraMotivazionale;
	private String letteraReferenziale;
	private Date dataInsert;
	private Date dataUpdate;

	public DatiSportivi() {
	}

	public DatiSportivi(Integer idDisciplineSportive, Integer idLivelliSportivi, String societaDiAppertenenza,
			Integer annoInizioAgonismo, Integer idPersone, String letteraMotivazionale, String letteraReferenziale,
			Date dataInsert, Date dataUpdate) {
		this.idDisciplineSportive = idDisciplineSportive;
		this.idLivelliSportivi = idLivelliSportivi;
		this.societaDiAppertenenza = societaDiAppertenenza;
		this.annoInizioAgonismo = annoInizioAgonismo;
		this.idPersone = idPersone;
		this.letteraMotivazionale = letteraMotivazionale;
		this.letteraReferenziale = letteraReferenziale;
		this.dataInsert = dataInsert;
		this.dataUpdate = dataUpdate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdDisciplineSportive() {
		return this.idDisciplineSportive;
	}

	public void setIdDisciplineSportive(Integer idDisciplineSportive) {
		this.idDisciplineSportive = idDisciplineSportive;
	}

	public Integer getIdLivelliSportivi() {
		return this.idLivelliSportivi;
	}

	public void setIdLivelliSportivi(Integer idLivelliSportivi) {
		this.idLivelliSportivi = idLivelliSportivi;
	}

	public String getSocietaDiAppertenenza() {
		return this.societaDiAppertenenza;
	}

	public void setSocietaDiAppertenenza(String societaDiAppertenenza) {
		this.societaDiAppertenenza = societaDiAppertenenza;
	}

	public Integer getAnnoInizioAgonismo() {
		return this.annoInizioAgonismo;
	}

	public void setAnnoInizioAgonismo(Integer annoInizioAgonismo) {
		this.annoInizioAgonismo = annoInizioAgonismo;
	}

	public Integer getIdPersone() {
		return this.idPersone;
	}

	public void setIdPersone(Integer idPersone) {
		this.idPersone = idPersone;
	}

	public String getLetteraMotivazionale() {
		return this.letteraMotivazionale;
	}

	public void setLetteraMotivazionale(String letteraMotivazionale) {
		this.letteraMotivazionale = letteraMotivazionale;
	}

	public String getLetteraReferenziale() {
		return this.letteraReferenziale;
	}

	public void setLetteraReferenziale(String letteraReferenziale) {
		this.letteraReferenziale = letteraReferenziale;
	}

	public Date getDataInsert() {
		return this.dataInsert;
	}

	public void setDataInsert(Date dataInsert) {
		this.dataInsert = dataInsert;
	}

	public Date getDataUpdate() {
		return this.dataUpdate;
	}

	public void setDataUpdate(Date dataUpdate) {
		this.dataUpdate = dataUpdate;
	}

}
