package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

/**
 * DisciplineSportive generated by hbm2java
 */
public class DisciplineSportive implements java.io.Serializable {

	private Integer id;
	private String sport;

	public DisciplineSportive() {
	}

	public DisciplineSportive(String sport) {
		this.sport = sport;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSport() {
		return this.sport;
	}

	public void setSport(String sport) {
		this.sport = sport;
	}

}
