package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * Fotografie generated by hbm2java
 */
public class Fotografie implements java.io.Serializable {

	private Integer id;
	private byte[] foto;
	private String contentType;
	private String format;
	private Integer idPersone;
	private Date dataInsert;
	private Date dataUpdate;

	public Fotografie() {
	}

	public Fotografie(byte[] foto, String contentType, String format, Integer idPersone, Date dataInsert,
			Date dataUpdate) {
		this.foto = foto;
		this.contentType = contentType;
		this.format = format;
		this.idPersone = idPersone;
		this.dataInsert = dataInsert;
		this.dataUpdate = dataUpdate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	public Integer getIdPersone() {
		return this.idPersone;
	}

	public void setIdPersone(Integer idPersone) {
		this.idPersone = idPersone;
	}

	public Date getDataInsert() {
		return this.dataInsert;
	}

	public void setDataInsert(Date dataInsert) {
		this.dataInsert = dataInsert;
	}

	public Date getDataUpdate() {
		return this.dataUpdate;
	}

	public void setDataUpdate(Date dataUpdate) {
		this.dataUpdate = dataUpdate;
	}

}
