package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * Indirizzi generated by hbm2java
 */
public class Indirizzi implements java.io.Serializable {

	private Integer id;
	private String indirizzo;
	private String civico;
	private String nazioniCodiceCatastale;
	private String comuniCodiceCatastale;
	private String comuneDenominazione;
	private String nazioneDenominazione;
	private String cap;
	private Integer idTipologieIndirizzi;
	private Integer idPersone;
	private Date dataInsert;
	private Date dataUpdate;

	public Indirizzi() {
	}

	public Indirizzi(String indirizzo, String civico, String nazioniCodiceCatastale, String comuniCodiceCatastale,
			String comuneDenominazione, String nazioneDenominazione, String cap, Integer idTipologieIndirizzi,
			Integer idPersone, Date dataInsert, Date dataUpdate) {
		this.indirizzo = indirizzo;
		this.civico = civico;
		this.nazioniCodiceCatastale = nazioniCodiceCatastale;
		this.comuniCodiceCatastale = comuniCodiceCatastale;
		this.comuneDenominazione = comuneDenominazione;
		this.nazioneDenominazione = nazioneDenominazione;
		this.cap = cap;
		this.idTipologieIndirizzi = idTipologieIndirizzi;
		this.idPersone = idPersone;
		this.dataInsert = dataInsert;
		this.dataUpdate = dataUpdate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	public String getCivico() {
		return this.civico;
	}

	public void setCivico(String civico) {
		this.civico = civico;
	}

	public String getNazioniCodiceCatastale() {
		return this.nazioniCodiceCatastale;
	}

	public void setNazioniCodiceCatastale(String nazioniCodiceCatastale) {
		this.nazioniCodiceCatastale = nazioniCodiceCatastale;
	}

	public String getComuniCodiceCatastale() {
		return this.comuniCodiceCatastale;
	}

	public void setComuniCodiceCatastale(String comuniCodiceCatastale) {
		this.comuniCodiceCatastale = comuniCodiceCatastale;
	}

	public String getComuneDenominazione() {
		return this.comuneDenominazione;
	}

	public void setComuneDenominazione(String comuneDenominazione) {
		this.comuneDenominazione = comuneDenominazione;
	}

	public String getNazioneDenominazione() {
		return this.nazioneDenominazione;
	}

	public void setNazioneDenominazione(String nazioneDenominazione) {
		this.nazioneDenominazione = nazioneDenominazione;
	}

	public String getCap() {
		return this.cap;
	}

	public void setCap(String cap) {
		this.cap = cap;
	}

	public Integer getIdTipologieIndirizzi() {
		return this.idTipologieIndirizzi;
	}

	public void setIdTipologieIndirizzi(Integer idTipologieIndirizzi) {
		this.idTipologieIndirizzi = idTipologieIndirizzi;
	}

	public Integer getIdPersone() {
		return this.idPersone;
	}

	public void setIdPersone(Integer idPersone) {
		this.idPersone = idPersone;
	}

	public Date getDataInsert() {
		return this.dataInsert;
	}

	public void setDataInsert(Date dataInsert) {
		this.dataInsert = dataInsert;
	}

	public Date getDataUpdate() {
		return this.dataUpdate;
	}

	public void setDataUpdate(Date dataUpdate) {
		this.dataUpdate = dataUpdate;
	}

}
