package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

/**
 * Labels generated by hbm2java
 */
public class Labels implements java.io.Serializable {

	private Integer id;
	private String lingueCodice;
	private Integer codiceLabel;
	private String label;

	public Labels() {
	}

	public Labels(String lingueCodice, Integer codiceLabel, String label) {
		this.lingueCodice = lingueCodice;
		this.codiceLabel = codiceLabel;
		this.label = label;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLingueCodice() {
		return this.lingueCodice;
	}

	public void setLingueCodice(String lingueCodice) {
		this.lingueCodice = lingueCodice;
	}

	public Integer getCodiceLabel() {
		return this.codiceLabel;
	}

	public void setCodiceLabel(Integer codiceLabel) {
		this.codiceLabel = codiceLabel;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

}
