package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

/**
 * LivelliSportivi generated by hbm2java
 */
public class LivelliSportivi implements java.io.Serializable {

	private Integer id;
	private String livello;

	public LivelliSportivi() {
	}

	public LivelliSportivi(String livello) {
		this.livello = livello;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLivello() {
		return this.livello;
	}

	public void setLivello(String livello) {
		this.livello = livello;
	}

}
