package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * MiurScuole generated by hbm2java
 */
public class MiurScuole implements java.io.Serializable {

	private Integer idScuola;
	private String codScuola;
	private String denominazione;
	private String tipoScuolaMiurCod;
	private Integer stataleFlg;
	private String regione;
	private String prov;
	private String comune;
	private String codIstatMiur;
	private String cap;
	private String indirizzo;
	private String telefono;
	private Integer statoCaric;
	private Date dataCaric;
	private String livelloFunzionale;
	private String codiceScuolaRiferimento;
	private String tipologia;
	private String tipologiaSede;
	private String parita;
	private String targa;
	private Integer idRegioni;
	private Integer idProvince;
	private Integer idComuni;

	public MiurScuole() {
	}

	public MiurScuole(Integer idScuola, Integer stataleFlg, String codIstatMiur, Integer statoCaric) {
		this.idScuola = idScuola;
		this.stataleFlg = stataleFlg;
		this.codIstatMiur = codIstatMiur;
		this.statoCaric = statoCaric;
	}

	public MiurScuole(Integer idScuola, String codScuola, String denominazione, String tipoScuolaMiurCod,
			Integer stataleFlg, String regione, String prov, String comune, String codIstatMiur, String cap,
			String indirizzo, String telefono, Integer statoCaric, Date dataCaric, String livelloFunzionale,
			String codiceScuolaRiferimento, String tipologia, String tipologiaSede, String parita, String targa,
			Integer idRegioni, Integer idProvince, Integer idComuni) {
		this.idScuola = idScuola;
		this.codScuola = codScuola;
		this.denominazione = denominazione;
		this.tipoScuolaMiurCod = tipoScuolaMiurCod;
		this.stataleFlg = stataleFlg;
		this.regione = regione;
		this.prov = prov;
		this.comune = comune;
		this.codIstatMiur = codIstatMiur;
		this.cap = cap;
		this.indirizzo = indirizzo;
		this.telefono = telefono;
		this.statoCaric = statoCaric;
		this.dataCaric = dataCaric;
		this.livelloFunzionale = livelloFunzionale;
		this.codiceScuolaRiferimento = codiceScuolaRiferimento;
		this.tipologia = tipologia;
		this.tipologiaSede = tipologiaSede;
		this.parita = parita;
		this.targa = targa;
		this.idRegioni = idRegioni;
		this.idProvince = idProvince;
		this.idComuni = idComuni;
	}

	public Integer getIdScuola() {
		return this.idScuola;
	}

	public void setIdScuola(Integer idScuola) {
		this.idScuola = idScuola;
	}

	public String getCodScuola() {
		return this.codScuola;
	}

	public void setCodScuola(String codScuola) {
		this.codScuola = codScuola;
	}

	public String getDenominazione() {
		return this.denominazione;
	}

	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione;
	}

	public String getTipoScuolaMiurCod() {
		return this.tipoScuolaMiurCod;
	}

	public void setTipoScuolaMiurCod(String tipoScuolaMiurCod) {
		this.tipoScuolaMiurCod = tipoScuolaMiurCod;
	}

	public Integer getStataleFlg() {
		return this.stataleFlg;
	}

	public void setStataleFlg(Integer stataleFlg) {
		this.stataleFlg = stataleFlg;
	}

	public String getRegione() {
		return this.regione;
	}

	public void setRegione(String regione) {
		this.regione = regione;
	}

	public String getProv() {
		return this.prov;
	}

	public void setProv(String prov) {
		this.prov = prov;
	}

	public String getComune() {
		return this.comune;
	}

	public void setComune(String comune) {
		this.comune = comune;
	}

	public String getCodIstatMiur() {
		return this.codIstatMiur;
	}

	public void setCodIstatMiur(String codIstatMiur) {
		this.codIstatMiur = codIstatMiur;
	}

	public String getCap() {
		return this.cap;
	}

	public void setCap(String cap) {
		this.cap = cap;
	}

	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Integer getStatoCaric() {
		return this.statoCaric;
	}

	public void setStatoCaric(Integer statoCaric) {
		this.statoCaric = statoCaric;
	}

	public Date getDataCaric() {
		return this.dataCaric;
	}

	public void setDataCaric(Date dataCaric) {
		this.dataCaric = dataCaric;
	}

	public String getLivelloFunzionale() {
		return this.livelloFunzionale;
	}

	public void setLivelloFunzionale(String livelloFunzionale) {
		this.livelloFunzionale = livelloFunzionale;
	}

	public String getCodiceScuolaRiferimento() {
		return this.codiceScuolaRiferimento;
	}

	public void setCodiceScuolaRiferimento(String codiceScuolaRiferimento) {
		this.codiceScuolaRiferimento = codiceScuolaRiferimento;
	}

	public String getTipologia() {
		return this.tipologia;
	}

	public void setTipologia(String tipologia) {
		this.tipologia = tipologia;
	}

	public String getTipologiaSede() {
		return this.tipologiaSede;
	}

	public void setTipologiaSede(String tipologiaSede) {
		this.tipologiaSede = tipologiaSede;
	}

	public String getParita() {
		return this.parita;
	}

	public void setParita(String parita) {
		this.parita = parita;
	}

	public String getTarga() {
		return this.targa;
	}

	public void setTarga(String targa) {
		this.targa = targa;
	}

	public Integer getIdRegioni() {
		return this.idRegioni;
	}

	public void setIdRegioni(Integer idRegioni) {
		this.idRegioni = idRegioni;
	}

	public Integer getIdProvince() {
		return this.idProvince;
	}

	public void setIdProvince(Integer idProvince) {
		this.idProvince = idProvince;
	}

	public Integer getIdComuni() {
		return this.idComuni;
	}

	public void setIdComuni(Integer idComuni) {
		this.idComuni = idComuni;
	}

}
