package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

/**
 * Nazioni generated by hbm2java
 */
public class Nazioni implements java.io.Serializable {

	private Integer id;
	private String codice;
	private String nazione;
	private String codiceCatastale;

	public Nazioni() {
	}

	public Nazioni(Integer id) {
		this.id = id;
	}

	public Nazioni(Integer id, String codice, String nazione, String codiceCatastale) {
		this.id = id;
		this.codice = codice;
		this.nazione = nazione;
		this.codiceCatastale = codiceCatastale;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	public String getNazione() {
		return this.nazione;
	}

	public void setNazione(String nazione) {
		this.nazione = nazione;
	}

	public String getCodiceCatastale() {
		return this.codiceCatastale;
	}

	public void setCodiceCatastale(String codiceCatastale) {
		this.codiceCatastale = codiceCatastale;
	}

}
