package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * Persone generated by hbm2java
 */
public class Persone implements java.io.Serializable {

	private Integer id;
	private String codiceFiscale;
	private String cognome;
	private String nome;
	private String sesso;
	private Date dataNascita;
	private String codiceCatastaleLuogoNascita;
	private String luogoNascita;
	private String codiceCatastaleNazioneNascita;
	private String nazioneNascita;
	private Date dataInsert;
	private Date dataUpdate;

	public Persone() {
	}

	public Persone(String codiceFiscale, String cognome, String nome, String sesso, Date dataNascita,
			String codiceCatastaleLuogoNascita, String luogoNascita, String codiceCatastaleNazioneNascita,
			String nazioneNascita) {
		this.codiceFiscale = codiceFiscale;
		this.cognome = cognome;
		this.nome = nome;
		this.sesso = sesso;
		this.dataNascita = dataNascita;
		this.codiceCatastaleLuogoNascita = codiceCatastaleLuogoNascita;
		this.luogoNascita = luogoNascita;
		this.codiceCatastaleNazioneNascita = codiceCatastaleNazioneNascita;
		this.nazioneNascita = nazioneNascita;
	}

	public Persone(String codiceFiscale, String cognome, String nome, String sesso, Date dataNascita,
			String codiceCatastaleLuogoNascita, String luogoNascita, String codiceCatastaleNazioneNascita,
			String nazioneNascita, Date dataInsert, Date dataUpdate) {
		this.codiceFiscale = codiceFiscale;
		this.cognome = cognome;
		this.nome = nome;
		this.sesso = sesso;
		this.dataNascita = dataNascita;
		this.codiceCatastaleLuogoNascita = codiceCatastaleLuogoNascita;
		this.luogoNascita = luogoNascita;
		this.codiceCatastaleNazioneNascita = codiceCatastaleNazioneNascita;
		this.nazioneNascita = nazioneNascita;
		this.dataInsert = dataInsert;
		this.dataUpdate = dataUpdate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCodiceFiscale() {
		return this.codiceFiscale;
	}

	public void setCodiceFiscale(String codiceFiscale) {
		this.codiceFiscale = codiceFiscale;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getSesso() {
		return this.sesso;
	}

	public void setSesso(String sesso) {
		this.sesso = sesso;
	}

	public Date getDataNascita() {
		return this.dataNascita;
	}

	public void setDataNascita(Date dataNascita) {
		this.dataNascita = dataNascita;
	}

	public String getCodiceCatastaleLuogoNascita() {
		return this.codiceCatastaleLuogoNascita;
	}

	public void setCodiceCatastaleLuogoNascita(String codiceCatastaleLuogoNascita) {
		this.codiceCatastaleLuogoNascita = codiceCatastaleLuogoNascita;
	}

	public String getLuogoNascita() {
		return this.luogoNascita;
	}

	public void setLuogoNascita(String luogoNascita) {
		this.luogoNascita = luogoNascita;
	}

	public String getCodiceCatastaleNazioneNascita() {
		return this.codiceCatastaleNazioneNascita;
	}

	public void setCodiceCatastaleNazioneNascita(String codiceCatastaleNazioneNascita) {
		this.codiceCatastaleNazioneNascita = codiceCatastaleNazioneNascita;
	}

	public String getNazioneNascita() {
		return this.nazioneNascita;
	}

	public void setNazioneNascita(String nazioneNascita) {
		this.nazioneNascita = nazioneNascita;
	}

	public Date getDataInsert() {
		return this.dataInsert;
	}

	public void setDataInsert(Date dataInsert) {
		this.dataInsert = dataInsert;
	}

	public Date getDataUpdate() {
		return this.dataUpdate;
	}

	public void setDataUpdate(Date dataUpdate) {
		this.dataUpdate = dataUpdate;
	}

}
