package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

/**
 * Regioni generated by hbm2java
 */
public class Regioni implements java.io.Serializable {

	private Integer id;
	private String regione;
	private Integer idNazioni;

	public Regioni() {
	}

	public Regioni(String regione, Integer idNazioni) {
		this.regione = regione;
		this.idNazioni = idNazioni;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRegione() {
		return this.regione;
	}

	public void setRegione(String regione) {
		this.regione = regione;
	}

	public Integer getIdNazioni() {
		return this.idNazioni;
	}

	public void setIdNazioni(Integer idNazioni) {
		this.idNazioni = idNazioni;
	}

}
