package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * RisultatiSportivi generated by hbm2java
 */
public class RisultatiSportivi implements java.io.Serializable {

	private Integer id;
	private String medaglia;
	private String descrizione;
	private Integer idDatiSportivi;
	private Date dataInsert;
	private Date dataUpdate;

	public RisultatiSportivi() {
	}

	public RisultatiSportivi(String medaglia, String descrizione, Integer idDatiSportivi, Date dataInsert,
			Date dataUpdate) {
		this.medaglia = medaglia;
		this.descrizione = descrizione;
		this.idDatiSportivi = idDatiSportivi;
		this.dataInsert = dataInsert;
		this.dataUpdate = dataUpdate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMedaglia() {
		return this.medaglia;
	}

	public void setMedaglia(String medaglia) {
		this.medaglia = medaglia;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Integer getIdDatiSportivi() {
		return this.idDatiSportivi;
	}

	public void setIdDatiSportivi(Integer idDatiSportivi) {
		this.idDatiSportivi = idDatiSportivi;
	}

	public Date getDataInsert() {
		return this.dataInsert;
	}

	public void setDataInsert(Date dataInsert) {
		this.dataInsert = dataInsert;
	}

	public Date getDataUpdate() {
		return this.dataUpdate;
	}

	public void setDataUpdate(Date dataUpdate) {
		this.dataUpdate = dataUpdate;
	}

}
