package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

/**
 * Sedi generated by hbm2java
 */
public class Sedi implements java.io.Serializable {

	private Integer id;
	private Integer idContesti;
	private String descrizione;
	private String visibile;

	public Sedi() {
	}

	public Sedi(Integer idContesti, String descrizione, String visibile) {
		this.idContesti = idContesti;
		this.descrizione = descrizione;
		this.visibile = visibile;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdContesti() {
		return this.idContesti;
	}

	public void setIdContesti(Integer idContesti) {
		this.idContesti = idContesti;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getVisibile() {
		return this.visibile;
	}

	public void setVisibile(String visibile) {
		this.visibile = visibile;
	}

}
