package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * Telefoni generated by hbm2java
 */
public class Telefoni implements java.io.Serializable {

	private Integer id;
	private Integer idPersone;
	private String telefono;
	private Date dataInsert;
	private Date dataUpdate;

	public Telefoni() {
	}

	public Telefoni(Integer idPersone, String telefono, Date dataInsert, Date dataUpdate) {
		this.idPersone = idPersone;
		this.telefono = telefono;
		this.dataInsert = dataInsert;
		this.dataUpdate = dataUpdate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdPersone() {
		return this.idPersone;
	}

	public void setIdPersone(Integer idPersone) {
		this.idPersone = idPersone;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Date getDataInsert() {
		return this.dataInsert;
	}

	public void setDataInsert(Date dataInsert) {
		this.dataInsert = dataInsert;
	}

	public Date getDataUpdate() {
		return this.dataUpdate;
	}

	public void setDataUpdate(Date dataUpdate) {
		this.dataUpdate = dataUpdate;
	}

}
