package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

/**
 * TipiTitoloSup generated by hbm2java
 */
public class TipiTitoloSup implements java.io.Serializable {

	private String tipoTitoloCod;
	private Integer idMacroTipo;
	private Integer idTipoIst;
	private Integer idTitolo;
	private String tipologiaCod;
	private String des;
	private Integer sysFlg;
	private Integer idDiploma;
	private Integer almaCod;
	private Integer annoIntFlg;
	private Integer abilVisFlg;

	public TipiTitoloSup() {
	}

	public TipiTitoloSup(String tipoTitoloCod) {
		this.tipoTitoloCod = tipoTitoloCod;
	}

	public TipiTitoloSup(String tipoTitoloCod, Integer idMacroTipo, Integer idTipoIst, Integer idTitolo,
			String tipologiaCod, String des, Integer sysFlg, Integer idDiploma, Integer almaCod, Integer annoIntFlg,
			Integer abilVisFlg) {
		this.tipoTitoloCod = tipoTitoloCod;
		this.idMacroTipo = idMacroTipo;
		this.idTipoIst = idTipoIst;
		this.idTitolo = idTitolo;
		this.tipologiaCod = tipologiaCod;
		this.des = des;
		this.sysFlg = sysFlg;
		this.idDiploma = idDiploma;
		this.almaCod = almaCod;
		this.annoIntFlg = annoIntFlg;
		this.abilVisFlg = abilVisFlg;
	}

	public String getTipoTitoloCod() {
		return this.tipoTitoloCod;
	}

	public void setTipoTitoloCod(String tipoTitoloCod) {
		this.tipoTitoloCod = tipoTitoloCod;
	}

	public Integer getIdMacroTipo() {
		return this.idMacroTipo;
	}

	public void setIdMacroTipo(Integer idMacroTipo) {
		this.idMacroTipo = idMacroTipo;
	}

	public Integer getIdTipoIst() {
		return this.idTipoIst;
	}

	public void setIdTipoIst(Integer idTipoIst) {
		this.idTipoIst = idTipoIst;
	}

	public Integer getIdTitolo() {
		return this.idTitolo;
	}

	public void setIdTitolo(Integer idTitolo) {
		this.idTitolo = idTitolo;
	}

	public String getTipologiaCod() {
		return this.tipologiaCod;
	}

	public void setTipologiaCod(String tipologiaCod) {
		this.tipologiaCod = tipologiaCod;
	}

	public String getDes() {
		return this.des;
	}

	public void setDes(String des) {
		this.des = des;
	}

	public Integer getSysFlg() {
		return this.sysFlg;
	}

	public void setSysFlg(Integer sysFlg) {
		this.sysFlg = sysFlg;
	}

	public Integer getIdDiploma() {
		return this.idDiploma;
	}

	public void setIdDiploma(Integer idDiploma) {
		this.idDiploma = idDiploma;
	}

	public Integer getAlmaCod() {
		return this.almaCod;
	}

	public void setAlmaCod(Integer almaCod) {
		this.almaCod = almaCod;
	}

	public Integer getAnnoIntFlg() {
		return this.annoIntFlg;
	}

	public void setAnnoIntFlg(Integer annoIntFlg) {
		this.annoIntFlg = annoIntFlg;
	}

	public Integer getAbilVisFlg() {
		return this.abilVisFlg;
	}

	public void setAbilVisFlg(Integer abilVisFlg) {
		this.abilVisFlg = abilVisFlg;
	}

}
