package luiss.it.LGCDB_Clienti.dao;
// Generated 11-dic-2018 16.15.27 by Hibernate Tools 5.2.6.Final

/**
 * Tokens generated by hbm2java
 */
public class Tokens implements java.io.Serializable {

	private String password;

	public Tokens() {
	}

	public Tokens(String password) {
		this.password = password;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
