package luiss.it.Attachments.dao;
// Generated 5-nov-2018 9.08.29 by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * Allegati generated by hbm2java
 */
public class Allegati implements java.io.Serializable {

	private Integer id;
	private String codiceFiscale;
	private byte[] allegato;
	private String contentType;
	private String descrizione;
	private String format;
	private Date dataInserimento;

	public Allegati() {
	}

	public Allegati(String codiceFiscale, byte[] allegato, String contentType, String descrizione, String format,
			Date dataInserimento) {
		this.codiceFiscale = codiceFiscale;
		this.allegato = allegato;
		this.contentType = contentType;
		this.descrizione = descrizione;
		this.format = format;
		this.dataInserimento = dataInserimento;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCodiceFiscale() {
		return this.codiceFiscale;
	}

	public void setCodiceFiscale(String codiceFiscale) {
		this.codiceFiscale = codiceFiscale;
	}

	public byte[] getAllegato() {
		return this.allegato;
	}

	public void setAllegato(byte[] allegato) {
		this.allegato = allegato;
	}

	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	public Date getDataInserimento() {
		return this.dataInserimento;
	}

	public void setDataInserimento(Date dataInserimento) {
		this.dataInserimento = dataInserimento;
	}

}
